### ISSUE TITLE
A suggestion on Emoji auto typing

### ISSUE THREAD

**Issue by vaaandark** [66RING/scripts#1]
https://github.com/66RING/scripts/blob/27988f0a49e35882013d62718fe5f06c9189b689/global/emoji-selector#L19

Maybe you can try command `xdotool type {{SOME_STRING}}` to auto type, rather than to save it in the clipboard.

**Comment by 66RING** [comment]
Good idea! Maybe I will add some kind of oneshot mode using this xdotool type, but save it somewhere and reuse it is more common in my case for now.
